### ISSUE TITLE
RPG - Données 2022

### ISSUE THREAD

**Issue by paul-carteron** [IGNF/apicarto#113]
Bonjour, 

[L'APICarto RPG](https://apicarto.ign.fr/api/doc/rpg) semble)être disfonctionnelle pour l'année 2022.

Lorsque je teste avec le géométrie : {"type": "Point","coordinates":[-1.691634,48.104237]} en 2021, la requête fonctionne et renvoi bien une géométrie NULL. Par contre pour l'année 2022, l'API renvoi une erreur type 500 :

```
{
  "type": "error",
  "message": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ows:ExceptionReport xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:ows=\"http://www.opengis.net/ows/1.1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"2.0.0\" xsi:schemaLocation=\"http://www.opengis.net/ows/1.1 https://data.geopf.fr/wfs/schemas/ows/1.1.0/owsAll.xsd\">\n<ows:Exception exceptionCode=\"InvalidParameterValue\" locator=\"GetFeature\">\n<ows:ExceptionText>Illegal property name: geom for feature type RPG.2022:parcelles_graphiques</ows:ExceptionText>\n</ows:Exception>\n</ows:ExceptionReport>\n"
}
```

Merci d'avance

**Comment by MFrangi** [comment]
Bonjour,

Merci pour votre retour.

Effectivement, il y a un dysfonctionnement dû à un nom d'attribut différent sur la ressource 2022. Le sujet est en cours d'investigation.

Cordialement,

Manuel

**Comment by MFrangi** [comment]
Issue traitée et solution déployée en production. La ressource RPG 2022 est désormais fonctionnelle.
