### ISSUE TITLE
GpU - SUP : Extraction du champ NOMSUPLITT

### ISSUE THREAD

**Issue by CGuillaume** [IGNF/apicarto#115]
Bonjour,

Je travaille avec l'API du GPU pour extraire les SUP présentes sur notre territoire, cela fonctionne super bien pour construire une table propre avec les liens vers les PDF des actes.

Toutefois après enquête, je ne retrouve pas le champs _NOMSUPLITT_ que l'on retrouve dans les archives que l'on télécharge depuis le GPU.

Par exemple pour les servitudes AC2 (cela est vrai pour les autres aussi), il y a une table AC2_SERVITUDE.dbf dans laquelle on retrouve notre champ _NOMSUPLITT_ avec un _IDSUP_ mais il n'apparait dans aucunes API des SUP (acte, assiette ou générateur)

![image](https://github.com/user-attachments/assets/383ba260-505d-4ea2-9e61-9940488d6e13)

A moins que je ne sois passé à coté, pensez-vous qu'il soit possible d'ajouter un moyen d'interroger cet attribut qui peut être bien utile pour l'utilisateur ?

Merci d'avance,

Guillaume COSTES
Responsable SIG
CA Grand Lac

**Comment by MFrangi** [comment]
Bonjour,

Si je comprends bien, vous utilisez la route `/gpu/acte-sup` du module GPU d'Apicarto. Effectivement, les données interrogées par cette route ne contiennent pas de champ `nomsuplitt`.
En revanche, les routes `/gpu/assiette-sup-s`, `/gpu/assiette-sup-l` et `/gpu/assiette-sup-p` renvoient cette information. N'avez-vous pas possibilité d'interroger ces routes ?

Exemple : 
https://apicarto.ign.fr/api/gpu/acte-sup?partition=110068012_SUP_28_A7 ne renvoie pas l'information `nomsuplitt`.
https://apicarto.ign.fr/api/gpu/assiette-sup-s?partition=110068012_SUP_28_A7 renvoie l'information `nomsuplitt`.

N'ayant que très peu de connaissance dans le domaine de l'urbanisme, j'espère avoir compris votre question. Si ce n'est pas le cas, n'hésitez pas à me le signaler.

**Comment by CGuillaume** [comment]
Bonjour,

J'utilise les deux routes /gpu/acte-sup et /gpu/assiette-sup-s et effectivement il y a bien l'information `nomsuplitt` pour l'assiette.
J'étais passé à coté car ce n'est pas indiqué dans la doc : https://apicarto.ign.fr/api/doc/pdf/docUser_moduleUrbanisme.pdf  p10 et 11

Merci pour votre réactivité, c'est parfait.
