### ISSUE TITLE
erreur API zone-urba sur certains polygones

### ISSUE THREAD

**Issue by 2803media** [IGNF/apicarto#20]
Bonjour

Je constate quelques erreurs 500 de l'api pour des polygones comme ces urls ci-dessous:

```https://apicarto.ign.fr/api/gpu/zone-urba?geom=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B2.3474897%2C49.4860581%5D%2C%5B2.347563%2C49.4862366%5D%2C%5B2.3475886%2C49.4862974%5D%2C%5B2.3476096%2C49.4863471%5D%2C%5B2.3474778%2C49.4863701%5D%2C%5B2.3472309%2C49.4864139%5D%2C%5B2.3472184%2C49.4864162%5D%2C%5B2.3470858%2C49.4864396%5D%2C%5B2.3468285%2C49.4864852%5D%2C%5B2.3467557%2C49.486498%5D%2C%5B2.3467116%2C49.4864445%5D%2C%5B2.346638%2C49.4863537%5D%2C%5B2.3465402%2C49.4862235%5D%2C%5B2.3466755%2C49.4861941%5D%2C%5B2.346807%2C49.4861657%5D%2C%5B2.3468592%2C49.4861545%5D%2C%5B2.3468941%2C49.4861469%5D%2C%5B2.3468918%2C49.4861421%5D%2C%5B2.3469253%2C49.486136%5D%2C%5B2.3470807%2C49.4861073%5D%2C%5B2.3471096%2C49.4861026%5D%2C%5B2.3474566%2C49.4860479%5D%2C%5B2.3474897%2C49.4860581%5D%5D%5D%7D```

ou 

```https://apicarto.ign.fr/api/gpu/zone-urba?geom=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B2.3390038%2C49.4857027%5D%2C%5B2.3373781%2C49.4889573%5D%2C%5B2.3371246%2C49.4890575%5D%2C%5B2.3368185%2C49.4891596%5D%2C%5B2.3350847%2C49.4898377%5D%2C%5B2.3344182%2C49.4901326%5D%2C%5B2.334192%2C49.4902192%5D%2C%5B2.3340144%2C49.4902688%5D%2C%5B2.3338488%2C49.4903148%5D%2C%5B2.3335409%2C49.4902819%5D%2C%5B2.3328821%2C49.4902599%5D%2C%5B2.3325469%2C49.4901804%5D%2C%5B2.3319606%2C49.4901652%5D%2C%5B2.3318516%2C49.4900689%5D%2C%5B2.3318303%2C49.4900589%5D%2C%5B2.3320036%2C49.4898535%5D%2C%5B2.3321448%2C49.4896174%5D%2C%5B2.3315985%2C49.4897158%5D%2C%5B2.3310198%2C49.489733%5D%2C%5B2.330952%2C49.489726%5D%2C%5B2.3306483%2C49.4896946%5D%2C%5B2.3302005%2C49.4895921%5D%2C%5B2.3301677%2C49.4895893%5D%2C%5B2.3300905%2C49.4895859%5D%2C%5B2.3293947%2C49.4895568%5D%2C%5B2.3293779%2C49.4893929%5D%2C%5B2.3293688%2C49.4893545%5D%2C%5B2.3292712%2C49.4893497%5D%2C%5B2.3288095%2C49.4894124%5D%2C%5B2.327488%2C49.4895799%5D%2C%5B2.3277033%2C49.489778%5D%2C%5B2.3277511%2C49.4898234%5D%2C%5B2.3276578%2C49.4898655%5D%2C%5B2.3266308%2C49.4890222%5D%2C%5B2.326791%2C49.4889408%5D%2C%5B2.3264127%2C49.4885999%5D%2C%5B2.3281482%2C49.4882182%5D%2C%5B2.328122%2C49.4881889%5D%2C%5B2.3279192%2C49.4879993%5D%2C%5B2.3277461%2C49.4877647%5D%2C%5B2.3277402%2C49.4877445%5D%2C%5B2.327927%2C49.4869591%5D%2C%5B2.3280352%2C49.4866157%5D%2C%5B2.328223%2C49.4863226%5D%2C%5B2.3287216%2C49.4857176%5D%2C%5B2.3287336%2C49.4857004%5D%2C%5B2.3288743%2C49.4854807%5D%2C%5B2.3298068%2C49.48388%5D%2C%5B2.3298927%2C49.4838501%5D%2C%5B2.3304293%2C49.4839497%5D%2C%5B2.331359%2C49.4840643%5D%2C%5B2.3318589%2C49.4841435%5D%2C%5B2.3334111%2C49.4844864%5D%2C%5B2.3342487%2C49.4846506%5D%2C%5B2.3376185%2C49.4854092%5D%2C%5B2.3390038%2C49.4857027%5D%5D%5D%7D```

Une idée du pourquoi de cette erreur?

On dirait que cela plante pour les gros polygones?

L'erreur est la suivante:

{
  "errno": "ECONNRESET",
  "code": "ECONNRESET",
  "syscall": "read",
  "config": {
    "transformRequest": {},
    "transformResponse": {},
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Referer": "https://apicarto.ign.fr/api/doc/gpu",
      "User-Agent": "apicarto"
    },
    "method": "get",
    "params": {
      "service": "WFS",
      "version": "2.0.0",
      "request": "GetFeature",
      "typename": "wfs_sup:acte_sup",
      "outputFormat": "application/json",
      "srsName": "CRS:84",
      "count": 100,
      "cql_filter": "INTERSECTS(the_geom,POLYGON ((49.4811171 2.3586573, 49.4741479 2.3578138, 49.4740793 2.3580891, 49.4741124 2.3581821, 49.4742942 2.3582539, 49.4745833 2.358386, 49.4753113 2.3588672, 49.4754949 2.3590149, 49.4757468 2.3589907, 49.4761457 2.359094, 49.4765545 2.359275, 49.4768224 2.3594123, 49.4771501 2.3595834, 49.4772107 2.3596202, 49.4776636 2.3598673, 49.4784899 2.3600785, 49.4786717 2.3601684, 49.4790748 2.3604464, 49.4792418 2.3605271, 49.4793342 2.3605697, 49.4794197 2.3606156, 49.4800993 2.3609967, 49.4801525 2.3609657, 49.4802099 2.3608258, 49.4805029 2.3600709, 49.48083 2.3593641, 49.4810182 2.3589255, 49.4811171 2.3586573)))"
    },
    "responseType": "text",
    "url": "http://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs/v"
  }
}

**Comment by mborne** [comment]
Bonjour,

Désolé pou l'absence de réponse, mais je constate que le problème semble résolu (probablement un passage sur des POST plutôt que des GET en coulisse depuis).

Merci de rouvrir en cas de problème, je ferme pour la visibilité sur les actions.
