### ISSUE TITLE
Ajouter des exemples  d'utilisation API CARTO

### ISSUE THREAD

**Issue by vinsag** [IGNF/apicarto#26]
L'objectif est d'ajouter des exemples d'utilisation de l' API CARTO:
 - Faire un exemple de recherche dans un rayon de x mètres autour d'un point.
 - Faire une recherche de x mètres par rapport au centroid d'une parcelle cadastrale
 - Exemple de calcul d'une surface d'une géométrie générée par un résultat.

- Ajouter un exemple de positionnement sur une carte et affichage de la géométrie.

**Comment by mborne** [comment]
Abandonné (le site de présentation https://apicarto.ign.fr a vocation à être refondu)

**Comment by ArnaudHureaux** [comment]
Je ne trouve nulle part d'exemple de requête sur cette API pourtant très prometteuse
