### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by chronotech-dev** [IGNF/apicarto#45]
Comment peut-on utiliser les identifiants et mot passe (fournis avec la clé) avec cette API ?

Les fournir dans l'URL ne fonctionne pas :
`https://[LOGIN]:[PASSWORD]@apicarto.ign.fr/api/cadastre/parcelle?apikey=[KEY]&geom=%7B%0D%0A++++++++%22type%22%3A+%22Point%22%2C%0D%0A++++++++%22coordinates%22%3A+%5B%0D%0A++++++++++0%2C%0D%0A++++++++++0%0D%0A++++++++%5D%0D%0A++++++%7D`

On obtient :
`{"type":"error","message":"<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"}`

**Comment by vinsag** [comment]
Bonjour,

Il faut que votre clé soit défini par referer et non par login et mot de passe. Une fois votre clé défini par referer, vous pourrez faire vos appels en https://apicarto.ign.fr/api/cadastre/parcelle?apikey=[KEY]....

Vincent Sagniez

**Comment by chronotech-dev** [comment]
> Bonjour,
> 
> Il faut que votre clé soit défini par referer et non par login et mot de passe. Une fois votre clé défini par referer, vous pourrez faire vos appels en [https://apicarto.ign.fr/api/cadastre/parcelle?apikey=[KEY]](https://apicarto.ign.fr/api/cadastre/parcelle?apikey=%5BKEY%5D)....
> 
> Vincent Sagniez

Effectivement, j'ai eu un réponse du support par mail entre temps et fait une demande de changement de mode de sécurisation de la clé.

Je suis maintenant en attente !

Merci pour votre aide :)

**Comment by mborne** [comment]
L'APICARTO s'appuie désormais sur des clés génériques.

Il n'est plus nécessaire de fournir une clé.

Je ferme ce ticket.

Cordialement,
