### ISSUE TITLE
Erreur 502 de manière intermittente sur la recuperation de parcelles

### ISSUE THREAD

**Issue by PaulQbFeng** [IGNF/apicarto#57]
Bonjour,

Quand j'essaie de récupérer des parcelles de la source PCI avec l'api carto j'ai souvent des erreurs 502 qui font que les appels vers le service ne sont pas stable du tout. 

Quand je lance la requête suivante 100 fois, j'aurai 13 fois une erreur 502:

https://apicarto.ign.fr:/api/cadastre/parcelle?geom=%7B%22type%22%3A+%22Polygon%22%2C+%22coordinates%22%3A+%5B%5B%5B3.9617672432981834%2C+49.042230243298185%5D%2C+%5B3.9617672432981834%2C+49.04095975670182%5D%2C+%5B3.960496756701817%2C+49.04095975670182%5D%2C+%5B3.960496756701817%2C+49.042230243298185%5D%2C+%5B3.9617672432981834%2C+49.042230243298185%5D%5D%5D%7D&source_ign=PCI

Arrivez vous a reproduire ce bug ? 

Merci

**Comment by vinsag** [comment]
Bonjour,
Nous n'avons pas constaté d'erreur 502 lors de lancement de requête. Quel est le mode opératoire que vous utilisez, lancez vous les requêtes les unes après les autres avec un intervalle de temps ou non ? Quand avez vous fait ce type de test, ca nous permettra de vérifier s'il n'y avait pas de problème à ce moment la ?

Cordialement,
Vincent Sagniez

**Comment by mborne** [comment]
Bonjour,

Désolé pour l'absence d'information, mais une optimisation a été appliquée au niveau de l'infrastructure réseau.

Depuis, nous n'observons plus ces erreurs aléatoires.

Cordialement,
