### ISSUE TITLE
acte-sup doesn't work with geom

### ISSUE THREAD

**Issue by paul-carteron** [IGNF/apicarto#58]
Bonjour,
L'API acte-sup du module urbanisme renvoi 0 features peu importe le géométrie fournie en entrée. Pourtant, les API assiette-sup-* sont fonctionnelles. Exemple ci-dessous : 

GEOM :
 {"type":"Polygon","coordinates":[[[-4.32312,47.876112],[-4.303894,47.798712],[-3.348083,47.957074],[-3.339844,48.423791],[-4.691162,48.037925],[-4.32312,47.876112]]]}

REQUETE ACTE-SUP (non fonctionnelle) :
https://apicarto.ign.fr/api/gpu/acte-sup?geom=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-4.32312%2C47.876112%5D%2C%5B-4.303894%2C47.798712%5D%2C%5B-3.348083%2C47.957074%5D%2C%5B-3.339844%2C48.423791%5D%2C%5B-4.691162%2C48.037925%5D%2C%5B-4.32312%2C47.876112%5D%5D%5D%7D

REQUETE ASSIETTE-SUP-S (fonctionnelle) :
https://apicarto.ign.fr/api/gpu/assiette-sup-s?geom=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-4.32312%2C47.876112%5D%2C%5B-4.303894%2C47.798712%5D%2C%5B-3.348083%2C47.957074%5D%2C%5B-3.339844%2C48.423791%5D%2C%5B-4.691162%2C48.037925%5D%2C%5B-4.32312%2C47.876112%5D%5D%5D%7D

Je reste à disposition pour faire d'éventuels tests,

Merci à vous !

**Comment by mborne** [comment]
Bonjour,

Désolé pour le temps de réponse. Faute de géométrie au niveau de la table ACTE-SUP, il n'est pas possible de réaliser un filtrage géométrique. Il est possible de remonter aux ACTE-SUP à l'aide d'une "partition" récupérée au niveau de ASSIETTE-SUP-S : 

https://apicarto.ign.fr/api/gpu/acte-sup?partition=130010002_SUP_R53_AC2

Je note le problème dans la documentation de l'API où il faudra supprimer le paramètre "geom" pour `/api/gpu/acte-sup`.

Cordialement,

**Comment by paul-carteron** [comment]
Super, merci à vous !
