### ISSUE TITLE
Erreur documentation

### ISSUE THREAD

**Issue by paul-carteron** [IGNF/apicarto#76]
Bonjour,
La [documentation de l'API Carto cadastre](https://apicarto.ign.fr/api/doc/cadastre) annonce qu'il est possible de récupérer : _le centroïde d’une parcelle ou d’une commune (localisants)_.

En testant l'API avec le paramètre code_insee, il n'ai pas possible d'obtenir le centroïde d'une commune car tous les centres de parcelles sont renvoyés.

**Comment by MFrangi** [comment]
Fermeture de l'issue : la doc ne mentionne plus la possibilité de récupérer le centroïde d'une commune.
