### ISSUE TITLE
GpU code siren optionnel

### ISSUE THREAD

**Issue by paul-carteron** [IGNF/apicarto#80]
Bonjour,
Dans la documentation utilisateur de l'APIcarto GpU, page 7, il est indiqué que la code siren (idGest) est optionnel pour la partition. Est-ce normal d'avoir une réponse uniquement quand le code optionnel est précisé ?

Renvoi de la donnée :
[https://apicarto.ign.fr/api/gpu/assiette-sup-s?partition=130007123_SUP_93_A7](https://apicarto.ign.fr/api/gpu/assiette-sup-s?partition=130007123_SUP_93_A7)

Ne renvoi pas de données : 
[https://apicarto.ign.fr/api/gpu/assiette-sup-s?partition=130007123_SUP_93_A7](https://apicarto.ign.fr/api/gpu/assiette-sup-s?partition=SUP_93_A7)

**Comment by vinsag** [comment]
Bonjour,
Le code Siren est devenu obligatoire. Une mise à jour de la documentation Api Carto Gpu est en cours.
Vincent

**Comment by paul-carteron** [comment]
Super, merci pour l'information !
