### ISSUE TITLE
Contenance doublée

### ISSUE THREAD

**Issue by seb-mynotary** [IGNF/apicarto#81]
La contenance retournée par l'api est doublée.

Je ne trouve pas d'info sur cet attribut dans la documentation.

Est ce possible d'avoir plus d'information svp.

**Comment by jlesech** [comment]
Il s'agit d'un bug, la contenance était correcte il y a quelques jours.

**Comment by seb-mynotary** [comment]
@vinsag Désolé de te tagger mais est ce que tu as plus d'info a ce sujet ?

Est ce qu'il y a un bug quelque part qu'on peut suivre ou contribuer ?

En attendant, on a divisé par 2 les valeurs mais j'ai peur du jour ou le fix va passer on va de nouveau avoir des valeurs erronées.

**Comment by jlesech** [comment]
Le problème est résolu. Intéressé aussi pour en connaître l'origine.

**Comment by MFrangi** [comment]
Fermeture de l'issue : le problème est apparemment résolu. Je n'ai pas d'info sur l'origine.
