### ISSUE TITLE
Temps de requête vers l'API très long.

### ISSUE THREAD

**Issue by Zeworxx** [IGNF/apicarto#98]
Bonjour, 

J'ai remarqué que le temps de réponse du serveur de l'API est assez long :

![image](https://github.com/IGNF/apicarto/assets/94362197/ac562eb9-b87d-4c99-93a0-7ea84a82c38a)

C'est assez aléatoire néanmoins cela peut prendre jusqu'à 1 minute.
De plus sur certaines requêtes effectuées, j'obtiens aléatoirement des 500 : 

![image](https://github.com/IGNF/apicarto/assets/94362197/3152b8c3-5966-496b-a31c-b73436fd2edb)

Merci d'avance pour votre réponse 👍 !

**Comment by MFrangi** [comment]
Bonjour,

Désolé pour le temps de réponse.

N'ayant pas de détail sur les requêtes effectuées, il n'est pas possible de reproduire le problème. Il s'agissait peut-être d'un ralentissement temporaire.

Si le problème est toujours présent, merci de bien vouloir ouvrir une nouvelle "issue" en précisant la requête concernée.
